# import = ["~/.config/alacritty/colors/dracula-pro.toml"]
import = ["~/.config/alacritty/colors/rose-pine-dawn.toml"]
# import = ["~/.config/alacritty/themes/themes/github_light.toml"]
# import = ["~/.config/alacritty/themes/themes/github_dark.toml"]
# import = ["~/.config/alacritty/themes/themes/nord.toml"]

[window]
decorations = "full"
option_as_alt = "OnlyLeft"
decorations_theme_variant = "None" # "None" will use the system choice

[font]
size = 14.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 9

[selection]
save_to_clipboard = true
