# import = ["~/.config/alacritty/colors/dracula-pro.toml"]
# import = ["~/.config/alacritty/colors/rose-pine-dawn.toml"]
import = ["~/.config/alacritty/themes/themes/gruvbox_material_hard_light.toml"]
# import = ["~/.config/alacritty/themes/themes/github_light.toml"]
# import = ["~/.config/alacritty/themes/themes/github_dark.toml"]
# import = ["~/.config/alacritty/themes/themes/nord.toml"]
# import = ["~/.config/alacritty/themes/themes/catppuccin_frappe.toml"]
# import = ["~/.config/alacritty/colors/catppuccin-latte.toml"]
# import = ["~/.config/alacritty/colors/dracula-pro-alucard.toml"]

[window]
decorations = "full"
option_as_alt = "OnlyLeft"
decorations_theme_variant = "None" # "None" will use the system choice

[font]
size = 15.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Light Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 8

[font.glyph_offset]
x = 0
y = 2

[selection]
save_to_clipboard = true
