[colors.primary]
background = "#212C2A"
foreground = "#F8F8F2"
bright_foreground = "#FFFFFF"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.search.matches]
foreground = "#415854"
background = "#8AFF80"

[colors.search.focused_match]
foreground = "#415854"
background = "#FFCA80"

[colors.footer_bar]
background = "#212C2A"
foreground = "#F8F8F2"

[colors.hints.start]
foreground = "#212C2A"
background = "#FFFF80"

[colors.hints.end]
foreground = "#FFFF80"
background = "#212C2A"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.selection]
text = "CellForeground"
background = "#415854"

[colors.normal]
black = "#70A99F"
red = "#FF9580"
green = "#8AFF80"
yellow = "#FFFF80"
blue = "#9580FF"
magenta = "#FF80BF"
cyan = "#80FFEA"
white = "#F8F8F2"

[colors.bright]
black = "#70A99F"
red = "#FFAA99"
green = "#A2FF99"
yellow = "#FFFF99"
blue = "#AA99FF"
magenta = "#FF99CC"
cyan = "#99FFEE"
white = "#FFFFFF"
