[battery]
disabled = true
[package]
disabled = true
[dotnet]
disabled = true
[elixir]
disabled = true
[elm]
disabled = true
[golang]
disabled = true
[java]
disabled = true
[nodejs]
disabled = true
[php]
disabled = true
[python]
disabled = false
[ruby]
disabled = true
[rust]
disabled = true
[terraform]
disabled = true
