#-----------------------------------------------------------
# General settings
#-----------------------------------------------------------
leader_key = "f18"        # required, the leader key that starts the sequence
leader_key_mods = ""      # optional, default "", not recommended - a dedicated leader key is better
                             # supports cmd ctrl alt shift
auto_reload = true        # optional, default true, reload when any file in this directory is saved
toast_on_reload = true    # optional, default false, show a toast when the config is reloaded
show_ui = true            # optional, default true, show the ui with your key maps
key_maps_per_line = 3     # optional, default 5, number of key maps per line in the ui

[d]
label = "+[d]diagram"
r = "function:insertReturnSequence"

#-----------------------------------------------------------
# Window management
#-----------------------------------------------------------
#
# | hs.layout.constant | key 1 | key 2 | mnemonic                             |
# | ------------------ | ----- | ----- | ------------------------------------ |
# | left25             | h     | 2     | \[h\] vim left \[2\]5 percent        |
# | left30             | h     | 3     | \[h\] vim left \[3\]0 percent        |
# | left50             | h     | h     | \[h\] vim left \[h\] vim left        |
# | left70             | h     | 7     | \[h\] vim left \[7\]0 percent        |
# | left75             | h     | 8     | \[h\] vim left \[8\]0 (ish) percent  |
# | maximized          | u     |       | \[u\]p - max the window go "up"      |
# | right25            | l     | 2     | \[h\] vim right \[2\]5 percent       |
# | right30            | l     | l     | \[h\] vim right \[l\]vim right       |
# | right50            | l     | 5     | \[h\] vim right \[5\]0 percent       |
# | right70            | l     | 7     | \[h\] vim right \[7\]0 percent       |
# | right75            | l     | 8     | \[h\] vim right \[8\]0 (ish) percent |
#-----------------------------------------------------------

# TODO(ljj): Hammerspoon does not have defaults for percentages from top or bottom.
# Create shortcuts for top50 and bottom50 that map to <leader>kk and <leader>jj respectively.

[w]
label = "+[w]indow"
u = "function:maximized"

[w.h]
label = "+[h] vim left"
2 = "function:left25"
3 = "function:left30"
h = "function:left50"
7 = "function:left70"
8 = "function:left75"

[w.l]
label = "+[l] vim right"
2 = "function:right25"
3 = "function:right30"
l = "function:right50"
7 = "function:right70"
8 = "function:right75"

#-----------------------------------------------------------
# Some of sample.toml copied here for now
#-----------------------------------------------------------

# create groups to nest actions
[l]
label = "[links]" # the "label" key is reserved to change the label of the group
g = "https://github.com"
b = "https://bsky.app"
t = "https://twitter.com"


# groups can be nested too!
[l.m]
label = "[me]"
g = ["https://github.com/saml-dev", "my github"]
b = ["https://bsky.app/profile/saml.dev", "my bluesky"]
t = ["https://twitter.com/saml_dev", "my twitter"]


# raycast deep links are supported
[r]
label = "[raycast]"
c = ["raycast://extensions/raycast/raycast/confetti", "confetti"]
e = ["raycast://extensions/raycast/emoji-symbols/search-emoji-symbols", "emoji"]
v = ["raycast://extensions/raycast/clipboard-history/clipboard-history", "clipboard"]


# use prefixes for special actions
[p]
label = "[prefixes]"
t = "text:sam@saml.dev"       # types "sam@saml.dev"
z = "cmd:code ~/.zshrc"       # run any terminal command
x = "code: ~/.zshrc"          # open a file or directory in VS Code
s = "shortcut:cmd shift 4"    # trigger a keyboard shortcut
w = "menu:File>New Window"    # select menu items (frontmost app)
n = "menu:Safari|File>New Tab" # select menu items (specific app)
r = "reload"                  # reserved for reloading your hammerspoon config (helpful when auto_reload is false)
i = "input:https://google.com/search?q={input}" # capture input and insert it into any other action


# this group is handy to copy over
# for quick access to your config
[h]
label = "[hammerspoon]"
r = "reload" # reserved for reloading your hammerspoon config (helpful when auto_reload is false)


# glhf :) share your cool ideas with me on
# twitter @saml_dev - <leader> l m t
# bluesky @saml.dev - <leader> l m b
# github saml-dev   - <leader> l m g


# for advanced hammerspoon users, you can use
# the hs: prefix as an escape hatch to run any
# hammerspoon command you want.
[z]
z = "hs:hs.alert('Hello, world!')"
